# Generated by Django 5.0.6 on 2024-06-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uno', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('loc', models.CharField(max_length=25)),
            ],
        ),
    ]
