# Generated by Django 5.0.6 on 2024-07-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=32)),
                ('uloc', models.CharField(max_length=32)),
            ],
        ),
    ]
